# Generated by Django 5.2.3 on 2025-06-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
